package top.hsyscn.opedrgent.model

import org.json.JSONObject

/**
 * 业余卫星通联日志条目（兼容 ADIF / Cabrillo / CSV 格式）
 *
 * 用于 Ham 模式下录制的通联转写文本解析后生成的结构化日志。
 * 可导出为标准 ADI 文件上传至 QRZLOG、LoTW 或 ClubLog。
 */
data class HamContactLog(
    /** 通联日期 (YYYY-MM-DD) */
    var date: String = "",
    /** 通联开始时间 (HHMMSS, UTC) */
    var timeOn: String = "",
    /** 通联结束时间 (HHMMSS, UTC) */
    var timeOff: String = "",
    /** 卫星名称 / 对方呼号 */
    var satName: String = "",
    /** 对方呼号（地面通联时使用） */
    var callsign: String = "",
    /** 下行频率 (MHz) */
    var frequency: String = "",
    /** 模式 (FM/SSB/CW/USB/LSB/APRS/GMSK等) */
    var mode: String = "",
    /** 发射信号报告 (RST 59/599等) */
    var rstSent: String = "",
    /** 接收信号报告 (RST 59/599等) */
    var rstReceived: String = "",
    /** 通联备注 */
    var notes: String = "",
    /** 网格定位 (如 PM01ab) */
    var gridLocator: String = "",
    /** 卫星 NORAD ID */
    var noradId: String = "",
    /** 最高仰角（度） */
    var maxElevation: String = "",
    /** 通联结果 (OK/_PARTIAL/NO) */
    var result: String = "",
) {
    /** 导出为 ADIF 格式记录 */
    fun toAdifRecord(): String {
        return buildString {
            appendField("QSO_DATE", date.replace("-", ""))
            appendField("TIME_ON", timeOn)
            appendField("TIME_OFF", timeOff)
            appendField("SAT_NAME", satName)
            appendField("CALL", callsign)
            appendField("FREQ", frequency)
            appendField("MODE", mode)
            appendField("RST_SENT", rstSent)
            appendField("RST_RCVD", rstReceived)
            appendField("GRIDSQUARE", gridLocator)
            appendField("NORAD_ID", noradId)
            appendField("MAX_ELEV", maxElevation)
            appendField("QSO_RESULT", result)
            appendField("NOTES", notes)
            appendField("STATION_CALLSIGN", "")
            appendField("MY_GRIDSQUARE", "")
            append("<EOR>\n")
        }
    }

    /** 导出为 CSV 格式行 */
    fun toCsvRow(): String {
        val cols = listOf(
            date, timeOn, timeOff, satName, callsign, frequency, mode,
            rstSent, rstReceived, notes, gridLocator, noradId, maxElevation, result
        )
        return cols.joinToString(",") { col ->
            val escaped = col.replace("\"", "\"\"")
            if (escaped.contains(",") || escaped.contains("\"")) "\"$escaped\"" else escaped
        }
    }

    private fun StringBuilder.appendField(tag: String, value: String) {
        if (value.isNotBlank()) {
            append("<$tag:${value.length}>$value ")
        }
    }

    companion object {
        val CSV_HEADER = "DATE,TIME_ON,TIME_OFF,SAT_NAME,CALL,FREQ,MODE,RST_SENT,RST_RCVD,NOTES,GRID,NORAD_ID,MAX_ELEV,RESULT"

        val ADIF_HEADER = buildString {
            appendLine("Generated by Opedrgent Ham Mode")
            appendLine("<ADIF_VER:5>3.1.4")
            appendLine("<PROGRAMID:8>Opedrgent")
            appendLine("<EOH>")
        }
    }
}
