package top.hsyscn.opedrgent.ui.components

data class DownloadQuote(
    val text: String,
    val author: String,
)

object DownloadQuotes {
    val ALL_QUOTES = listOf(
        DownloadQuote("山重水复疑无路，柳暗花明又一村。", "陆游"),
        DownloadQuote("长风破浪会有时，直挂云帆济沧海。", "李白"),
        DownloadQuote("千淘万漉虽辛苦，吹尽狂沙始到金。", "刘禹锡"),
        DownloadQuote("宝剑锋从磨砺出，梅花香自苦寒来。", "《警世贤文》"),
        DownloadQuote("路漫漫其修远兮，吾将上下而求索。", "屈原"),
        DownloadQuote("锲而不舍，金石可镂。", "荀子"),
        DownloadQuote("博观而约取，厚积而薄发。", "苏轼"),
        DownloadQuote("不积跬步，无以至千里；不积小流，无以成江海。", "荀子"),
        DownloadQuote("行到水穷处，坐看云起时。", "王维"),
        DownloadQuote("海内存知己，天涯若比邻。", "王勃"),
        DownloadQuote("沉舟侧畔千帆过，病树前头万木春。", "刘禹锡"),
        DownloadQuote("莫道桑榆晚，为霞尚满天。", "刘禹锡"),
        DownloadQuote("千磨万击还坚劲，任尔东西南北风。", "郑燮"),
        DownloadQuote("咬定青山不放松，立根原在破岩中。", "郑燮"),
        DownloadQuote("欲穷千里目，更上一层楼。", "王之涣"),
        DownloadQuote("会当凌绝顶，一览众山小。", "杜甫"),
        DownloadQuote("不畏浮云遮望眼，自缘身在最高层。", "王安石"),
        DownloadQuote("大鹏一日同风起，扶摇直上九万里。", "李白"),
        DownloadQuote("长风万里送秋雁，对此可以酣高楼。", "李白"),
        DownloadQuote("天生我材必有用，千金散尽还复来。", "李白"),
        DownloadQuote("休言万事转头空，未转头时皆梦。", "辛弃疾"),
        DownloadQuote("青山遮不住，毕竟东流去。", "辛弃疾"),
        DownloadQuote("众里寻他千百度，蓦然回首，那人却在灯火阑珊处。", "辛弃疾"),
        DownloadQuote("竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", "苏轼"),
        DownloadQuote("回首向来萧瑟处，归去，也无风雨也无晴。", "苏轼"),
        DownloadQuote("一点浩然气，千里快哉风。", "苏轼"),
        DownloadQuote("古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。", "苏轼"),
        DownloadQuote("人有悲欢离合，月有阴晴圆缺，此事古难全。", "苏轼"),
        DownloadQuote("谁道人生无再少？门前流水尚能西。", "黄庭坚"),
        DownloadQuote("春色满园关不住，一枝红杏出墙来。", "叶绍翁"),
        DownloadQuote("问渠那得清如许？为有源头活水来。", "朱熹"),
        DownloadQuote("等闲识得东风面，万紫千红总是春。", "朱熹"),
        DownloadQuote("纸上得来终觉浅，绝知此事要躬行。", "陆游"),
        DownloadQuote("位卑未敢忘忧事，事定犹须待阖棺。", "陆游"),
        DownloadQuote("僵卧孤村不自哀，尚思为国戍轮台。", "陆游"),
        DownloadQuote("出师一表真名世，千载谁堪伯仲间。", "陆游"),
        DownloadQuote("当年万里觅封侯，匹马戍梁州。", "陆游"),
        DownloadQuote("关河梦断何处？尘暗旧貂裘。", "陆游"),
        DownloadQuote("胡未灭，鬓先秋，泪空流。", "陆游"),
        DownloadQuote("此身合是诗人未？细雨骑驴入剑门。", "陆游"),
        DownloadQuote("小荷才露尖尖角，早有蜻蜓立上头。", "杨万里"),
        DownloadQuote("接天莲叶无穷碧，映日荷花别样红。", "杨万里"),
        DownloadQuote("正入万山圈子里，一山放过一山拦。", "杨万里"),
        DownloadQuote("莫言下岭便无难，赚得行人空喜欢。", "杨万里"),
        DownloadQuote("力微任重久神疲，再竭衰庸定不支。", "褚遂良"),
        DownloadQuote("老骥伏枥，志在千里；烈士暮年，壮心不已。", "曹操"),
        DownloadQuote("盈缩之期，不但在天；养怡之福，可得永年。", "曹操"),
        DownloadQuote("周公吐哺，天下归心。", "曹操"),
        DownloadQuote("秋风萧瑟天气凉，草木摇落露为霜。", "曹丕"),
        DownloadQuote("志士惜日短，愁人知夜长。", "傅玄"),
        DownloadQuote("盛年不重来，一日难再晨。", "陶渊明"),
        DownloadQuote("及时当勉励，岁月不待人。", "陶渊明"),
        DownloadQuote("采菊东篱下，悠然见南山。", "陶渊明"),
        DownloadQuote("问君何能尔？心远地自偏。", "陶渊明"),
        DownloadQuote("好读书，不求甚解；每有会意，便欣然忘食。", "陶渊明"),
        DownloadQuote("精卫衔微木，将以填沧海。", "陶渊明"),
        DownloadQuote("刑天舞干戚，猛志固常在。", "陶渊明"),
        DownloadQuote("闲寂古池边，青蛙跃入水声响。", "松尾芭蕉"),
        DownloadQuote("春雨绵绵落，紫丁香上露珠悬。", "与谢芜村"),
        DownloadQuote("秋风拂过处，落叶舞翩跹。", ""),
        DownloadQuote("站在风口上，猪都能飞起来。", "雷军"),
        DownloadQuote("专注、极致、口碑、快。", "雷军"),
        DownloadQuote("一个人可能走得更快，但一群人走，才能走得更远。", "雷军"),
        DownloadQuote("Are you OK?", "雷军"),
        DownloadQuote("把技术做到极致，让用户觉得无可挑剔。", "雷军"),
        DownloadQuote("工程师之魂就是比亚迪之魂。即便我们所有财产全部消失，只要工程师还在，就随时可以东山再起。", "王传福"),
        DownloadQuote("敢想、敢干、敢坚持。", "王传福"),
        DownloadQuote("快鱼吃慢鱼。市场经济的核心就是竞争，竞争才能产生繁荣。", "王传福"),
        DownloadQuote("进化，不是为了变得更强，而是为了活下去。", "刘润"),
        DownloadQuote("不要爱上你的产品，要爱上用户的需求。", "刘润"),
        DownloadQuote("该省省，该花花，骑着自行车去酒吧。", "刘润"),
        DownloadQuote("与其在枯草地上内卷，不如换张卷子答题。", "刘润"),
        DownloadQuote("AI不是对手，是伙伴；不是挤压，是托举。", "罗振宇"),
        DownloadQuote("在AI时代，谁离真实问题近，谁才捧得住金饭碗。", "罗振宇"),
        DownloadQuote("AI不是工具，而是伙伴。", "罗振宇"),
        DownloadQuote("AI不是把人往外挤，而是把人往上托。", "罗振宇"),
        DownloadQuote("AI一日三惊，你怎么还无动于衷？", "万维钢"),
        DownloadQuote("到2025年年底，AI的智力水平将超越任何单个人类。", "马斯克"),
        DownloadQuote("在AI的帮助下，我们正迈向彻底的富足时代。", "哈萨比斯"),
        DownloadQuote("当AI变得主动，它和人的关系将彻底发生颠覆。", "罗振宇"),
        DownloadQuote("这个世界正在变成一个巨大的3D打印机，你有想法就行，AI负责帮你实现，所想即所得。", "罗振宇"),
        DownloadQuote("AI技术革命的爆发场景，社会的各个场景都有可能，人人都有机会。", "罗振宇"),
        DownloadQuote("AI的门槛挺高，但是用好AI的门槛并不高。", "罗振宇"),
        DownloadQuote("AI是帮助你完成工作的打工人而已，你需要审阅，你可以让它重复修改，你需要签字承担责任。", "罗振宇"),
        DownloadQuote("悲观不过是一种看法，乐观才是引领我们前行的行动。", "罗振宇"),
        DownloadQuote("1000天后的强大竞争力，在于懂得让AI成为你并肩同行的伙伴。", "罗振宇"),
        DownloadQuote("智能的真正本质，是机器紧紧贴着人的心意运转。", "罗振宇"),
        DownloadQuote("让AI成为你的得力秘书，而你永远是自己人生的主宰。", "罗振宇"),
        DownloadQuote("AI非常棒！要是能替我去坐牢，就更棒了。", "罗振宇"),
        DownloadQuote("应用喂养智能，手在前，脑在后才是人类进化的本质。", "罗振宇"),
        DownloadQuote("AI替代的是标准化能力，放大的是人的独特价值。", "罗振宇"),
        DownloadQuote("人浮于世，AI是水，我是船，永远行于其上。", "罗振宇"),
        DownloadQuote("减肥这事急不得，慢慢来，会很快。", "罗振宇"),
        DownloadQuote("随时都是可以闯的年纪。", "罗振宇"),
        DownloadQuote("每一个普通的改变，都将改变普通。", "罗振宇"),
        DownloadQuote("事贵持之以恒，成长永远稀缺。", "罗振宇"),
        DownloadQuote("我经历的一切，才组合成此刻的我，少一点都不是我。", "罗振宇"),
        DownloadQuote("我一生的使命，就是要发明一个全世界只有我最胜任的职业。", "罗振宇"),
        DownloadQuote("攒一件如果没有你，就没有的事儿。", "罗振宇"),
        DownloadQuote("你能想象出大海的样子，就能想象这个世界任何地方的样子。", "陈行甲"),
        DownloadQuote("在世界的空白地带，填上人的愿力。", "罗振宇"),
        DownloadQuote("思想者的工作，在于设想最好的可能；乐天派的天性，在于拔腿就朝它前进。", "罗振宇"),
        DownloadQuote("虽千万人，吾往矣。", "引用孟子"),
        DownloadQuote("一直游到海水变蓝。", "引用余华"),
        DownloadQuote("心向山海，马踏生花。", "罗振宇"),
        DownloadQuote("读好书，听人劝。", "罗振宇"),
        DownloadQuote("我想慢下来，我不想变得麻木。", "罗振宇"),
        DownloadQuote("不要指望诺亚方舟，我就是我的诺亚方舟。", "罗振宇"),
        DownloadQuote("长期主义的双向奔赴，同频同行，方得长远。", "罗振宇"),
        DownloadQuote("天下第一等好事，还是读书！", "罗振宇"),
        DownloadQuote("活得具体，活得有热气，就是对抗AI时代的最好方式。", "罗振宇"),
        DownloadQuote("中年之问：我还有半生要过，我打算怎么过？", "罗振宇"),
        DownloadQuote("听身体的话，身体比大脑更诚实。", "罗振宇"),
        DownloadQuote("苦难可怖，但它标记了我们，使我们变得宽广。", "罗振宇"),
        DownloadQuote("体验永远是稀缺的，多去创造人生的第一次可能性。", "罗振宇"),
        DownloadQuote("破卷的终极秘诀，不是和别人拼赛道，而是做好自己的答卷。", "罗振宇"),
        DownloadQuote("头拱地干下去，让自己成为无可替代的产品。", "罗振宇"),
        DownloadQuote("敢想敢干，探索边界，你永远不会被AI替代。", "罗振宇"),
        DownloadQuote("过去，谁能高屋建瓴，谁是精英；现在，谁能理解一线场景，谁捧得住金饭碗。", "罗振宇"),
        DownloadQuote("人如何担责，可能会演化为一个专业，甚至一门生意。", "和菜头"),
        DownloadQuote("打造生意的底层操作系统，让每个生意人都拥有专属生意智能体验。", "罗振宇"),
        DownloadQuote("风浪皆过，基业恒稳，以万变成就不变。", "罗振宇"),
        DownloadQuote("因远见，而稳健。", "罗振宇"),
        DownloadQuote("未来工作的重心，将从执行转向定义问题和校准方向。", "罗振宇"),
        DownloadQuote("AI替代的是白领的标准化能力，催生的是紫领的独特价值。", "罗振宇"),
        DownloadQuote("离一线越近，离真实问题越近，离机会就越近。", "罗振宇"),
        DownloadQuote("人类的核心竞争力：可信赖、知进退、顾周全。", "罗振宇"),
        DownloadQuote("能拍板、能担责、能校准，才是不可替代的决策者。", "罗振宇"),
        DownloadQuote("不要和AI比效率，要和AI比想法、比愿力、比担当。", "罗振宇"),
        DownloadQuote("你的不可替代性，藏在你的独特阅历和躬身入局里。", "罗振宇"),
        DownloadQuote("定义问题比解决问题重要，校准方向比执行任务重要。", "罗振宇"),
        DownloadQuote("职场终极能力：让AI干活，为结果负责。", "罗振宇"),
        DownloadQuote("慢慢来，会很快。", "罗振宇"),
        DownloadQuote("AI是水，我们是船，水涨只会船高。", "罗振宇"),
        DownloadQuote("好东西，就要来了。", ""),
        DownloadQuote("您的模型正在部署，请放宽心坐。", ""),
        DownloadQuote("伟大的事物值得等待。", ""),
        DownloadQuote("正在从云端搬运智慧...", ""),
        DownloadQuote("罗马不是一天建成的。", ""),
        DownloadQuote("千里之行，始于足下。", "老子"),
        DownloadQuote("天下难事，必作于易；天下大事，必作于细。", "老子"),
        DownloadQuote("合抱之木，生于毫末；九层之台，起于累土。", "老子"),
        DownloadQuote("天行健，君子以自强不息。", "《周易》"),
        DownloadQuote("地势坤，君子以厚德载物。", "《周易》"),
        DownloadQuote("学而不思则罔，思而不学则殆。", "孔子"),
        DownloadQuote("工欲善其事，必先利其器。", "孔子"),
        DownloadQuote("逝者如斯夫，不舍昼夜。", "孔子"),
        DownloadQuote("岁寒，然后知松柏之后凋也。", "孔子"),
        DownloadQuote("知之为知之，不知为不知，是知也。", "孔子"),
        DownloadQuote("学而时习之，不亦说乎？", "孔子"),
        DownloadQuote("有朋自远方来，不亦乐乎？", "孔子"),
        DownloadQuote("三人行，必有我师焉。", "孔子"),
        DownloadQuote("默而识之，学而不厌，诲人不倦。", "孔子"),
        DownloadQuote("温故而知新，可以为师矣。", "孔子"),
        DownloadQuote("朝闻道，夕死可矣。", "孔子"),
        DownloadQuote("发愤忘食，乐以忘忧，不知老之将至云尔。", "孔子"),
        DownloadQuote("三军可夺帅也，匹夫不可夺志也。", "孔子"),
        DownloadQuote("后生可畏，焉知来者之不如今也？", "孔子"),
        DownloadQuote("四海之内，皆兄弟也。", "子夏"),
        DownloadQuote("青出于蓝而胜于蓝，冰水为之而寒于水。", "荀子"),
        DownloadQuote("驽马十驾，功在不舍。", "荀子"),
        DownloadQuote("蓬生麻中，不扶而直；白沙在涅，与之俱黑。", "荀子"),
        DownloadQuote("积土成山，风雨兴焉；积水成渊，蛟龙生焉。", "荀子"),
        DownloadQuote("不登高山，不知天之高也；不临深溪，不知地之厚也。", "荀子"),
        DownloadQuote("吾尝终日而思矣，不如须臾之所学也。", "荀子"),
        DownloadQuote("假舆马者，非利足也，而致千里；假舟楫者，非能水也，而绝江河。", "荀子"),
        DownloadQuote("骐骥一跃，不能十步；驽马十驾，功在不舍。", "荀子"),

        // ---- 新增：古诗词与经典名句 ----
        DownloadQuote("仰天大笑出门去，我辈岂是蓬蒿人。", "李白"),
        DownloadQuote("人生如逆旅，我亦是行人。", "苏轼"),
        DownloadQuote("时人不识凌云木，直待凌云始道高。", "杜荀鹤"),
        DownloadQuote("不经一番寒彻骨，怎得梅花扑鼻香。", "黄蘖禅师"),
        DownloadQuote("千锤万凿出深山，烈火焚烧若等闲。", "于谦"),
        DownloadQuote("老当益壮，宁移白首之心？穷且益坚，不坠青云之志。", "王勃"),
        DownloadQuote("少年负壮气，奋烈自有时。", "李白"),
        DownloadQuote("宁可枝头抱香死，何曾吹落北风中。", "郑思肖"),
        DownloadQuote("江东子弟多才俊，卷土重来未可知。", "杜牧"),
        DownloadQuote("黄沙百战穿金甲，不破楼兰终不还。", "王昌龄"),
        DownloadQuote("黑发不知勤学早，白首方悔读书迟。", "颜真卿"),
        DownloadQuote("读书破万卷，下笔如有神。", "杜甫"),
        DownloadQuote("笔落惊风雨，诗成泣鬼神。", "杜甫"),
        DownloadQuote("苔花如米小，也学牡丹开。", "袁枚"),
        DownloadQuote("历览前贤国与家，成由勤俭破由奢。", "李商隐"),
        DownloadQuote("不以物喜，不以己悲。", "范仲淹"),
        DownloadQuote("胜人者有力，自胜者强。", "《道德经》"),
        DownloadQuote("志不强者智不达。", "《墨子》"),
        DownloadQuote("满招损，谦受益。", "《尚书》"),
        DownloadQuote("玩人丧德，玩物丧志。", "《尚书》"),
        DownloadQuote("穷则独善其身，达则兼善天下。", "《孟子》"),
        DownloadQuote("君子喻于义，小人喻于利。", "《论语》"),
        DownloadQuote("见贤思齐焉，见不贤而内自省也。", "《论语》"),
        DownloadQuote("勿以恶小而为之，勿以善小而不为。", "刘备"),
        DownloadQuote("二人同心，其利断金。", "《周易》"),
        DownloadQuote("君子藏器于身，待时而动。", "《周易》"),
        DownloadQuote("天下兴亡，匹夫有责。", "顾炎武"),
        DownloadQuote("人生自古谁无死，留取丹心照汗青。", "文天祥"),

        // ---- 新增：日本俳句 ----
        DownloadQuote("我庭小草复萌发，无限天地行将绿。", "小林一茶"),
        DownloadQuote("雪融艳一点，当归淡紫芽。", "松尾芭蕉"),
        DownloadQuote("章鱼壶中梦黄粱，天边夏月。", "松尾芭蕉"),
        DownloadQuote("渡船春雨至，船上伞高低。", "与谢芜村"),

        // ---- 新增：现代名言 ----
        DownloadQuote("想象力比知识更重要。", "爱因斯坦"),
        DownloadQuote("成功不是终点，失败也并非末日，重要的是继续前进的勇气。", "丘吉尔"),
        DownloadQuote("教育是改变世界最有力的武器。", "曼德拉"),
        DownloadQuote("当某件事足够重要时，即使成功率不高，你也要去做。", "马斯克"),
        DownloadQuote("你见过凌晨四点的洛杉矶吗？", "科比"),
        DownloadQuote("今天很残酷，明天更残酷，而后天会很美好。", "马云"),
        DownloadQuote("其实地上本没有路，走的人多了，也便成了路。", "鲁迅"),
        DownloadQuote("人生应该如蜡烛一样，从顶燃到底，一直都是光明的。", "萧楚女"),
        DownloadQuote("天才出于勤奋。", "高尔基"),
        DownloadQuote("勤劳一日，可得一夜安眠；勤劳一生，可得幸福长眠。", "达·芬奇"),
        DownloadQuote("如果你因失去了太阳而流泪，那么你也将失去群星了。", "泰戈尔"),
        DownloadQuote("海纳百川，有容乃大；壁立千仞，无欲则刚。", "林则徐"),
        DownloadQuote("人有逆天之时，天无绝人之路。", "冯梦龙"),
        DownloadQuote("世上没有后悔药，但有预防药。", ""),
    )

    fun getRandomQuote(): DownloadQuote = ALL_QUOTES.random()

    fun getQuoteByIndex(index: Int): DownloadQuote =
        ALL_QUOTES[index.coerceIn(0, ALL_QUOTES.size - 1)]

    val size: Int get() = ALL_QUOTES.size
}
